#!/bin/bash

#-vars required for udocker
UDOCKER_IMG="my-image-name"
UDOCKER_TAG="my-image-tag"
UDOCKER_CTR="my-container-name"
#-

#-vars not used by udocker
# path to custom dockerfile
  __my_dockerfile="$(pwd)/my-dockerfile"
# path to directory to mount in container
  __my_workingdir_src="$(pwd)/my-working-directory"
  __my_workingdir_dst="/i-work-here"
#-

#-vars optional for udocker
UDOCKER_BUILD_FLAGS="-f $__my_dockerfile"
UDOCKER_RUN_FLAGS="-it --rm -d -v $__my_workingdir_src:$__my_workingdir_dst"
UDOCKER_EXEC_FLAGS="-it"
#-