#!/bin/bash

# wrapper for udocker that uses 'my-udocker-cfg'
# alternatively we can 'source my-udocker-cfg' and udocker will recognize defined variables
function logmsg() { printf "[my-udocker.msg] %s" "$*";     }
function logerr() { printf "[my-udocker.err] %s" "$*" >&2; }

if ! (command -v udocker &> /dev/null) ; then
  logerr "UDocker wasn't installed\n"
  exit 1
fi

source my-udocker-cfg
case $1 in 
  run) {
    [[ "$2" == "-d" || "$2" == "--detach" ]] && {
      logmsg "Running detached container\n"
      UDOCKER_RUN_FLAGS="--detach $UDOCKER_RUN_FLAGS"
    }
    udocker run bash
  };;
  bash) {
    udocker exec bash
  };;
  *) {
    udocker "$@"
  };;
esac