#!/bin/bash

export UDOCKER_IMAGE="my-image-name"
export UDOCKER_TAG="my-image-tag"
export UDOCKER_CONTAINER="my-container-name"

__my_dockerfile="$(pwd)/my-dockerfile"
__my_workingdir_src="$(pwd)/my-working-directory"
__my_workingdir_dst="/i-work-here"
__my_ssh="$HOME/.ssh"

export UDOCKER_NAME="my-udocker"
export UDOCKER_BUILD_OPTS="-f $__my_dockerfile"
export UDOCKER_RUN_OPTS="-it --rm -v $__my_workingdir_src:$__my_workingdir_dst -v $__my_ssh:~/.ssh -w /root"
export UDOCKER_EXEC_OPTS="-it"