#!/bin/bash
echo "==== Obtaining UDocker ===="
exe=udocker
url=https://raw.githubusercontent.com/infinitus-inanis/udocker/main/$exe
pushd /tmp > /dev/null
  curl -s $url -o $exe
  install_dir=${DESTDIR:-}${PREFIX:-/usr}/bin
  install_path=$install_dir/$exe
  install -d $install_dir
  install -m 755 $exe $install_dir
  if [ $? -eq 0 ]; then
    echo "== Installed at: $install_path"
  else
    echo "== Failed to install at: $install_path"
  fi
  rm -f $exe
popd > /dev/null
